### GET /
GET http://localhost:5003

### Register a new user
POST http://localhost:5003/auth/register
Content-Type: application/json

{ "username": "Temidayo@gmail.com", "password": "123123123" }

### Login as a user
POST http://localhost:5003/auth/login
Content-Type: application/json

{ "username": "Temidayo@gmail.com", "password": "123123123" }

### Create a new todo
POST http://localhost:5003/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM1ODEzODcxLCJleHAiOjE3MzU5MDAyNzF9.La1zGbjZQXvPvdCg0B_hntU3SQlghKLnXnTfjstfoIs

{ "task": "buy bread every single day" }

### Get all the todos
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM1ODEzODcxLCJleHAiOjE3MzU5MDAyNzF9.La1zGbjZQXvPvdCg0B_hntU3SQlghKLnXnTfjstfoIs


### Update a particular todo with id 
PUT http://localhost:5003/todos/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM1ODEzODcxLCJleHAiOjE3MzU5MDAyNzF9.La1zGbjZQXvPvdCg0B_hntU3SQlghKLnXnTfjstfoIs

{"completed": 1}


### Delete a particular todo with id
DELETE http://localhost:5003/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM1ODEzODcxLCJleHAiOjE3MzU5MDAyNzF9.La1zGbjZQXvPvdCg0B_hntU3SQlghKLnXnTfjstfoIs

